version: "3.7"
services:
  simplon-postgres:
    image: postgres
    container_name: "simplon-postgres"
    volumes:
      - simplon-postgres-volume:/var/lib/postgresql/data
    env_file:
      - config/variables.env
    ports:
      - ${POSTGRES_PORT}:5432
  simplon-pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: "simplon-pgadmin"
    env_file:
      - config/variables.env
    ports:
      - ${PGADMIN_PORT}:80
volumes:
  simplon-postgres-volume:
