version: "3.7"
services:
  simplon-postgres:
    image: postgres
    container_name: "${POSTGRES_DB}-postgres"
    volumes:
      - simplon-postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
  simplon-pgadmin:
    image: simplon-pgadmin
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
    container_name: "${POSTGRES_DB}-pgadmin"
    env_file:
      - .env
    ports:
      - ${PGADMIN_PORT}:80
    links:
      - simplon-postgres:simplon-postgres
volumes:
  simplon-postgres-volume:
